config/routes.rb
Hikakusan::Application.routes.draw do
  resources :item_columns

  resources :types

  resources :columns

  resources :items do
    member do
      post 'edit_complete'
    end
  end

  resources :tables do
    member do
      get 'add_column'
      get 'add_item'
      post 'add_item_complete'
    end
  end

  

end

app/models/column.rb
class Column < ActiveRecord::Base
  belongs_to :table
  has_many :item_columns, :dependent => :destroy
end

app/controllers/columns_controller.rb
class ColumnsController < ApplicationController
  before_action :set_column, only: [:show, :edit, :update, :destroy]

  # GET /columns
  # GET /columns.json
  def index
    @columns = Column.all
  end

  # GET /columns/1
  # GET /columns/1.json
  def show
  end

  # GET /columns/new
  def new
    @column = Column.new
  end

  # GET /columns/1/edit
  def edit
  end

  # POST /columns
  # POST /columns.json
  def create
    @column = Column.new(column_params)

    respond_to do |format|
      if @column.save
        format.html { redirect_to @column, notice: 'Column was successfully created.' }
        format.json { render action: 'show', status: :created, location: @column }
      else
        format.html { render action: 'new' }
        format.json { render json: @column.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /columns/1
  # PATCH/PUT /columns/1.json
  def update
    respond_to do |format|
      if @column.update(column_params)
        format.html { redirect_to @column, notice: 'Column was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @column.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /columns/1
  # DELETE /columns/1.json
  def destroy
    @column.destroy
    respond_to do |format|
      format.html { redirect_to columns_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_column
      @column = Column.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def column_params
      params.require(:column).permit(:table_id, :name, :type_id, :not_null, :unique, :unit, :default_value)
    end
end

app/helpers/columns_helper.rb
module ColumnsHelper
end

app/views/columns/_form.html.erb
<%= form_for(@column) do |f| %>
  <% if @column.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@column.errors.count, "error") %> prohibited this column from being saved:</h2>

      <ul>
      <% @column.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :table_id %><br>
    <%= f.number_field :table_id %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :type_id %><br>
    <%= f.number_field :type_id %>
  </div>
  <div class="field">
    <%= f.label :not_null %><br>
    <%= f.check_box :not_null %>
  </div>
  <div class="field">
    <%= f.label :unique %><br>
    <%= f.check_box :unique %>
  </div>
  <div class="field">
    <%= f.label :unit %><br>
    <%= f.text_field :unit %>
  </div>
  <div class="field">
    <%= f.label :default_value %><br>
    <%= f.text_field :default_value %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/columns/edit.html.erb
<h1>Editing column</h1>

<%= render 'form' %>

<%= link_to 'Show', @column %> |
<%= link_to 'Back', columns_path %>

app/views/columns/index.html.erb
<h1>Listing columns</h1>

<table>
  <thead>
    <tr>
      <th>Table</th>
      <th>Name</th>
      <th>Type</th>
      <th>Not null</th>
      <th>Unique</th>
      <th>Unit</th>
      <th>Default value</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @columns.each do |column| %>
      <tr>
        <td><%= column.table_id %></td>
        <td><%= column.name %></td>
        <td><%= column.type_id %></td>
        <td><%= column.not_null %></td>
        <td><%= column.unique %></td>
        <td><%= column.unit %></td>
        <td><%= column.default_value %></td>
        <td><%= link_to 'Show', column %></td>
        <td><%= link_to 'Edit', edit_column_path(column) %></td>
        <td><%= link_to 'Destroy', column, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Column', new_column_path %>

app/views/columns/new.html.erb
<h1>New column</h1>

<%= render 'form' %>

<%= link_to 'Back', columns_path %>

app/views/columns/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Table:</strong>
  <%= @column.table_id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @column.name %>
</p>

<p>
  <strong>Type:</strong>
  <%= @column.type_id %>
</p>

<p>
  <strong>Not null:</strong>
  <%= @column.not_null %>
</p>

<p>
  <strong>Unique:</strong>
  <%= @column.unique %>
</p>

<p>
  <strong>Unit:</strong>
  <%= @column.unit %>
</p>

<p>
  <strong>Default value:</strong>
  <%= @column.default_value %>
</p>

<%= link_to 'Edit', edit_column_path(@column) %> |
<%= link_to 'Back', columns_path %>