config/routes.rb
Hikakusan::Application.routes.draw do
  resources :item_columns

  resources :types

  resources :columns

  resources :items do
    member do
      post 'edit_complete'
    end
  end

  resources :tables do
    member do
      get 'add_column'
      get 'add_item'
      post 'add_item_complete'
    end
  end

  

end

app/controllers/tables_controller.rb
class TablesController < ApplicationController
  before_action :set_table, only: [:show, :edit, :update, :destroy, :add_item, :add_item_complete]

  # GET /tables
  # GET /tables.json
  def index
    @tables = Table.all
  end

  # GET /tables/1
  # GET /tables/1.json
  def show
    @columns = @table.columns
    @item_columns = Hash.new
    @table.item_columns.each do |ic|
      unless @item_columns[ic.item_id]
        @item_columns[ic.item_id] = Hash.new
      end
      @item_columns[ic.item_id][ic.column_id] = ic.value
    end
  end

  # GET /tables/new
  def new
    @table = Table.new
  end

  # GET /tables/1/edit
  def edit
  end

  # POST /tables
  # POST /tables.json
  def create
    @table = Table.new(table_params)

    respond_to do |format|
      if @table.save
        format.html { redirect_to @table, notice: 'Table was successfully created.' }
        format.json { render action: 'show', status: :created, location: @table }
      else
        format.html { render action: 'new' }
        format.json { render json: @table.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tables/1
  # PATCH/PUT /tables/1.json
  def update
    respond_to do |format|
      if @table.update(table_params)
        format.html { redirect_to @table, notice: 'Table was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @table.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tables/1
  # DELETE /tables/1.json
  def destroy
    @table.destroy
    respond_to do |format|
      format.html { redirect_to tables_url }
      format.json { head :no_content }
    end
  end

  def add_column
    @column = Column.new
    @column.table_id = params[:id]
  end

  def add_item
  end

  def add_item_complete
    @item = Item.new
    @item.table_id = params[:item][:table_id]
    @item.name = params[:item][:name]
    @item.save
    @table.columns.each do |column|
      value = params[:column][column.id.to_s]
      ItemColumn.create(:table_id => @table.id,
                        :item_id => @item.id,
                        :column_id => column.id,
                        :value => value)
    end
    redirect_to @table
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_table
      @table = Table.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def table_params
      params.require(:table).permit(:name, :key_column_name)
    end
end

app/helpers/tables_helper.rb
module TablesHelper
end

app/views/tables/_form.html.erb
<%= form_for(@table) do |f| %>
  <% if @table.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@table.errors.count, "error") %> prohibited this table from being saved:</h2>

      <ul>
      <% @table.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :key_column_name %><br>
    <%= f.text_field :key_column_name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tables/add_column.html.erb
<%= form_for(@column) do |f| %>
  <% if @column.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@column.errors.count, "error") %> prohibited this column from being saved:</h2>

      <ul>
      <% @column.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= hidden_field :column, :table_id %>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :type_id %><br>
    <%= f.number_field :type_id %>
  </div>
  <div class="field">
    <%= f.label :not_null %><br>
    <%= f.check_box :not_null %>
  </div>
  <div class="field">
    <%= f.label :unique %><br>
    <%= f.check_box :unique %>
  </div>
  <div class="field">
    <%= f.label :unit %><br>
    <%= f.text_field :unit %>
  </div>
  <div class="field">
    <%= f.label :default_value %><br>
    <%= f.text_field :default_value %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tables/add_item.html.erb
<h1>
  <%= @table.name %>
</h1>

<%= form_tag(add_item_complete_table_path(@table)) do %>
  <%= @table.key_column_name %>: 
  <%= text_field(:item, :name) %></br>
  <%= hidden_field_tag 'item[table_id]', "#{@table.id}" %>
  <% @table.columns.each do |column| %>
    <%= column.name %>: 
    <%= text_field(:column, "#{column.id}") %>
    <br>
  <% end %>
  <%= submit_tag %>
<% end %>

app/views/tables/edit.html.erb
<h1>Editing table</h1>

<%= render 'form' %>

<%= link_to 'Show', @table %> |
<%= link_to 'Back', tables_path %>

app/views/tables/index.html.erb
<h1>Listing tables</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @tables.each do |table| %>
      <tr>
        <td><%= table.name %></td>
        <td><%= link_to 'Show', table %></td>
        <td><%= link_to 'Edit', edit_table_path(table) %></td>
        <td><%= link_to 'Destroy', table, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Table', new_table_path %>

app/views/tables/new.html.erb
<h1>New table</h1>

<%= render 'form' %>

<%= link_to 'Back', tables_path %>

app/views/tables/show.html.erb
<p id="notice"><%= notice %></p>

<p>
<strong>Name:</strong>
<%= @table.name %>
</p>

<p>
<table border="1">
  <th>
    <%= @table.key_column_name %>
  </th>
  <% @columns.each do |column| %>
    <th>
      <%= link_to column.name, edit_column_path(column) %>
    </th>
  <% end %>
  <% @table.items.each do |item| %>
    <tr>
      <td>
        <%= link_to item.name, edit_item_path(item) %>
      </td>
      <% @columns.each do |column| %>
        <td>
          <%= @item_columns[item.id][column.id] %>
        </td>
      <% end %>
    </tr>
  <% end %>
</table>
</p>

<%= link_to 'Add Column', add_column_table_path(@table) %>
<%= link_to 'Add Item', add_item_table_path(@table) %>
<%= link_to 'Edit', edit_table_path(@table) %> 
<%= link_to 'Back', tables_path %>