config/routes.rb
Hikakusan::Application.routes.draw do
  resources :item_columns

  resources :types

  resources :columns

  resources :items do
    member do
      post 'edit_complete'
    end
  end

  resources :tables do
    member do
      get 'add_column'
      get 'add_item'
      post 'add_item_complete'
    end
  end

  

end

app/models/item_column.rb
class ItemColumn < ActiveRecord::Base
  belongs_to :table
  belongs_to :column
  belongs_to :item
end

app/controllers/item_columns_controller.rb
class ItemColumnsController < ApplicationController
  before_action :set_item_column, only: [:show, :edit, :update, :destroy]

  # GET /item_columns
  # GET /item_columns.json
  def index
    @item_columns = ItemColumn.all
  end

  # GET /item_columns/1
  # GET /item_columns/1.json
  def show
  end

  # GET /item_columns/new
  def new
    @item_column = ItemColumn.new
  end

  # GET /item_columns/1/edit
  def edit
  end

  # POST /item_columns
  # POST /item_columns.json
  def create
    @item_column = ItemColumn.new(item_column_params)

    respond_to do |format|
      if @item_column.save
        format.html { redirect_to @item_column, notice: 'Item column was successfully created.' }
        format.json { render action: 'show', status: :created, location: @item_column }
      else
        format.html { render action: 'new' }
        format.json { render json: @item_column.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /item_columns/1
  # PATCH/PUT /item_columns/1.json
  def update
    respond_to do |format|
      if @item_column.update(item_column_params)
        format.html { redirect_to @item_column, notice: 'Item column was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @item_column.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /item_columns/1
  # DELETE /item_columns/1.json
  def destroy
    @item_column.destroy
    respond_to do |format|
      format.html { redirect_to item_columns_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item_column
      @item_column = ItemColumn.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_column_params
      params.require(:item_column).permit(:table_id, :item_id, :column_id, :value)
    end
end

app/helpers/item_columns_helper.rb
module ItemColumnsHelper
end

app/views/item_columns/_form.html.erb
<%= form_for(@item_column) do |f| %>
  <% if @item_column.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item_column.errors.count, "error") %> prohibited this item_column from being saved:</h2>

      <ul>
      <% @item_column.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :table_id %><br>
    <%= f.number_field :table_id %>
  </div>
  <div class="field">
    <%= f.label :item_id %><br>
    <%= f.number_field :item_id %>
  </div>
  <div class="field">
    <%= f.label :column_id %><br>
    <%= f.number_field :column_id %>
  </div>
  <div class="field">
    <%= f.label :value %><br>
    <%= f.text_field :value %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/item_columns/edit.html.erb
<h1>Editing item_column</h1>

<%= render 'form' %>

<%= link_to 'Show', @item_column %> |
<%= link_to 'Back', item_columns_path %>

app/views/item_columns/index.html.erb
<h1>Listing item_columns</h1>

<table>
  <thead>
    <tr>
      <th>Table</th>
      <th>Item</th>
      <th>Column</th>
      <th>Value</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @item_columns.each do |item_column| %>
      <tr>
        <td><%= item_column.table_id %></td>
        <td><%= item_column.item_id %></td>
        <td><%= item_column.column_id %></td>
        <td><%= item_column.value %></td>
        <td><%= link_to 'Show', item_column %></td>
        <td><%= link_to 'Edit', edit_item_column_path(item_column) %></td>
        <td><%= link_to 'Destroy', item_column, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Item column', new_item_column_path %>

app/views/item_columns/new.html.erb
<h1>New item_column</h1>

<%= render 'form' %>

<%= link_to 'Back', item_columns_path %>

app/views/item_columns/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Table:</strong>
  <%= @item_column.table_id %>
</p>

<p>
  <strong>Item:</strong>
  <%= @item_column.item_id %>
</p>

<p>
  <strong>Column:</strong>
  <%= @item_column.column_id %>
</p>

<p>
  <strong>Value:</strong>
  <%= @item_column.value %>
</p>

<%= link_to 'Edit', edit_item_column_path(@item_column) %> |
<%= link_to 'Back', item_columns_path %>