config/routes.rb
Hikakusan::Application.routes.draw do
  resources :item_columns

  resources :types

  resources :columns

  resources :items do
    member do
      post 'edit_complete'
    end
  end

  resources :tables do
    member do
      get 'add_column'
      get 'add_item'
      post 'add_item_complete'
    end
  end

  

end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :table
  has_many :item_columns, :dependent => :destroy
end

app/controllers/items_controller.rb
require 'ostruct'

class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy, :edit_complete]

  # GET /items
  # GET /items.json
  def index
    @items = Item.all
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
    @table = @item.table
    column_hash = Hash.new
    @item.item_columns.each do |ic|
      column_hash["#{ic.column_id}"] = ic.value
    end
    @column = OpenStruct.new column_hash
  end

  def edit_complete
    @item.name = params[:item][:name]
    @item.save
    table = @item.table
    table.columns.each do |column|
      value = params[:column][column.id.to_s]
      ic = ItemColumn.where(["table_id = ? and item_id = ? and column_id = ?",
                            table.id,
                            @item.id,
                            column.id]).first
      ic.value = value
      ic.save
    end
    redirect_to table
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render action: 'show', status: :created, location: @item }
      else
        format.html { render action: 'new' }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:name, :table_id)
    end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= form_for(@item) do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :table_id %><br>
    <%= f.number_field :table_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing item</h1>

<%= form_tag(edit_complete_item_path(@item)) do %>
  <%= @table.key_column_name %>: 
  <%= text_field(:item, :name) %></br>
  <%= hidden_field_tag 'item[table_id]', "#{@table.id}" %>
  <% @table.columns.each do |column| %>
    <%= column.name %>: 
    <%= text_field(:column, "#{column.id}") %>
    <br>
  <% end %>
  <%= submit_tag %>
<% end %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', tables_path %>

app/views/items/index.html.erb
<h1>Listing items</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Table</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.name %></td>
        <td><%= item.table_id %></td>
        <td><%= link_to 'Show', item %></td>
        <td><%= link_to 'Edit', edit_item_path(item) %></td>
        <td><%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Item', new_item_path %>

app/views/items/new.html.erb
<h1>New item</h1>

<%= render 'form' %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @item.name %>
</p>

<p>
  <strong>Table:</strong>
  <%= @item.table_id %>
</p>

<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>